# Generated by Django 4.1.7 on 2023-03-24 16:13

import BarApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drankjes',
            fields=[
                ('drankjes_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=128)),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('img', image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=BarApp.models.img_filename)),
                ('ratio', image_cropping.fields.ImageRatioField('img', '286x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='ratio')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Drankjes',
                'db_table': 'Drankjes',
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': "Saldo's",
                'db_table': 'Saldo',
            },
        ),
        migrations.CreateModel(
            name='Transacties',
            fields=[
                ('transactie_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('saldo_voor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldo_na', models.DecimalField(decimal_places=2, max_digits=5)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bought_by', to=settings.AUTH_USER_MODEL)),
                ('drankje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarApp.drankjes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transacties',
                'db_table': 'Transacties',
            },
        ),
        migrations.CreateModel(
            name='Tikkie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tikkies',
                'db_table': 'Tikkies',
            },
        ),
        migrations.CreateModel(
            name='Stortingen',
            fields=[
                ('storting_id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_voor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldo_na', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Executed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stortingen',
                'db_table': 'Stortingen',
            },
        ),
    ]
