# Generated by Django 4.1.7 on 2023-03-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0002_transacties_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacties',
            name='drankje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarApp.drankjes'),
        ),
    ]
