# Generated by Django 4.1 on 2023-03-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarApp', '0002_rename_storing_amount_stortingen_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drankjes',
            options={'verbose_name_plural': 'Drankjes'},
        ),
        migrations.AlterModelOptions(
            name='saldo',
            options={'verbose_name_plural': "Saldo's"},
        ),
        migrations.AlterModelOptions(
            name='stortingen',
            options={'verbose_name_plural': 'Stortingen'},
        ),
        migrations.AlterModelOptions(
            name='transacties',
            options={'verbose_name_plural': 'Transacties'},
        ),
        migrations.CreateModel(
            name='Tikkie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tikkies',
                'db_table': 'Tikkies',
            },
        ),
    ]
