# Generated by Django 4.1 on 2023-03-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0003_alter_drankjes_options_alter_saldo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drankjes',
            name='img',
            field=models.ImageField(default='a', upload_to='images/'),
            preserve_default=False,
        ),
    ]
