# Generated by Django 4.1 on 2023-03-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0003_alter_drankjes_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankjes',
            name='active',
            field=models.BooleanField(),
        ),
    ]
