# Generated by Django 4.1 on 2023-03-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarApp', '0004_drankjes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='drankjes',
            name='dateTime',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drankjes',
            name='done_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
