# Generated by Django 4.1.7 on 2023-03-20 16:44

import BarApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0005_drankjes_datetime_drankjes_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankjes',
            name='img',
            field=models.ImageField(blank=True, upload_to=BarApp.models.img_filename),
        ),
    ]
