# Generated by Django 4.1 on 2023-03-23 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarApp', '0005_alter_drankjes_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacties',
            name='done_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Bought_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
