# Generated by Django 4.1 on 2023-03-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0006_transacties_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacties',
            name='saldo_na',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacties',
            name='saldo_voor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
