# Generated by Django 4.1.7 on 2023-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0006_alter_drankjes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='drankjes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
