# Generated by Django 4.1.7 on 2023-03-21 13:25

import BarApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0008_alter_drankjes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankjes',
            name='img',
            field=models.ImageField(blank=True, upload_to=BarApp.models.img_filename),
        ),
    ]
