# Generated by Django 4.1.7 on 2023-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarApp', '0010_alter_drankjes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankjes',
            name='img',
            field=models.ImageField(upload_to='drinks/%Y/%m/%d'),
        ),
    ]
